/**
* @NOTICE: DO NOT MODIFY THIS FILE
* Autogenerated with @amjs/api-parser
* @created 2019-07-16T10:36:45.141Z
*/
const { equal } = require('assert');
const { AmjsDataTypesCollection } = require('@amjs/data-types');
const AmjsFactory = require('@amjs/factory');
const AmjsApiParserTypeCollectionUsers = require('../../../../src/type/collection/Users');

(function()
{
    let sut = new AmjsApiParserTypeCollectionUsers();
    equal(sut instanceof AmjsDataTypesCollection, true,
        'AmjsApiParserTypeCollectionUsers extends AmjsDataTypesCollection');

    sut = AmjsFactory.create('AmjsApiParserTypeCollectionUsers');
    equal(sut instanceof AmjsApiParserTypeCollectionUsers, true,
        'Is registered as "AmjsApiParserTypeCollectionUsers"');
}());

(function()
{
    const sut = new AmjsApiParserTypeCollectionUsers();
    equal(sut.$itemType === 'User', true,
        `$itemType equals "User"`);
}());