/**
 * @NOTICE: DO NOT MODIFY THIS FILE
 * Autogenerated with @amjs/api-parser
 * @created 2019-07-16T10:36:45.141Z
 */
const { equal }                     = require('assert');
const { AmjsDataTypesObject }       = require('@amjs/data-types');
const AmjsFactory                   = require('@amjs/factory');
const AmjsApiParserTypeItemError    = require('../../../../src/type/item/Error');

(function()
{
    let sut = new AmjsApiParserTypeItemError();
    equal(sut instanceof AmjsDataTypesObject, true, 'AmjsApiParserTypeItemError extends AmjsDataTypesObject');

    sut = AmjsFactory.create('AmjsApiParserTypeItemError');
    equal(sut instanceof AmjsApiParserTypeItemError, true, 'Is registered as "AmjsApiParserTypeItemError"');
}());

(function()
{
    const sut = new AmjsApiParserTypeItemError();
    [
        'code',
        'message',
    ].forEach(prop => equal(prop in sut, true, `Property "${prop}" exists in instance`));
}());

(function()
{
    const sut = new AmjsApiParserTypeItemError();
    const propertyTypes = {
        code: 'Number',
        message: 'String',
    };
    Object.keys(propertyTypes).forEach(
        prop =>
            equal(sut.$propertyTypes[prop] === propertyTypes[prop], true,
                `Property "${prop}" has assigned a type of "${propertyTypes[prop]}"`));
}());
