/**
 * @NOTICE: DO NOT MODIFY THIS FILE
 * Autogenerated with @amjs/api-parser
 * @created 2019-07-16T10:36:45.141Z
 */
const { equal }                     = require('assert');
const { AmjsDataTypesObject }       = require('@amjs/data-types');
const AmjsFactory                   = require('@amjs/factory');
const AmjsApiParserTypeItemUser    = require('../../../../src/type/item/User');

(function()
{
    let sut = new AmjsApiParserTypeItemUser();
    equal(sut instanceof AmjsDataTypesObject, true, 'AmjsApiParserTypeItemUser extends AmjsDataTypesObject');

    sut = AmjsFactory.create('AmjsApiParserTypeItemUser');
    equal(sut instanceof AmjsApiParserTypeItemUser, true, 'Is registered as "AmjsApiParserTypeItemUser"');
}());

(function()
{
    const sut = new AmjsApiParserTypeItemUser();
    [
        'id',
        'name',
    ].forEach(prop => equal(prop in sut, true, `Property "${prop}" exists in instance`));
}());

(function()
{
    const sut = new AmjsApiParserTypeItemUser();
    const propertyTypes = {
        id: 'Number',
        name: 'String',
    };
    Object.keys(propertyTypes).forEach(
        prop =>
            equal(sut.$propertyTypes[prop] === propertyTypes[prop], true,
                `Property "${prop}" has assigned a type of "${propertyTypes[prop]}"`));
}());
